<?php

declare(strict_types=1);

namespace App\Command;

use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\Attribute\Autowire;

/**
 * Generates the application secrets that must not live in the committed .env (SPEC.md § 16.1, § 22).
 *
 * Values are written to .env.local and never overwritten unless --force is given, so the command is
 * idempotent and safe to run from "make install" on every setup.
 */
#[AsCommand(
    name: 'patchnotes:secrets:generate',
    description: 'Generate missing application secrets (APP_SECRET, APP_ENCRYPTION_KEY) into .env.local',
)]
final class GenerateSecretsCommand extends Command
{
    public function __construct(
        #[Autowire('%kernel.project_dir%')]
        private readonly string $projectDir,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->addOption('force', null, InputOption::VALUE_NONE, 'Replace secrets that are already set');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $force = (bool) $input->getOption('force');
        $envLocal = $this->projectDir.'/.env.local';

        $existing = is_file($envLocal) ? (file_get_contents($envLocal) ?: '') : '';
        $generated = [];

        $secrets = [
            // 64 hex characters, the format Symfony uses for APP_SECRET.
            'APP_SECRET' => static fn (): string => bin2hex(random_bytes(32)),
            // libsodium secretbox key for the encrypted profile tags (SPEC.md § 10, § 24.8).
            'APP_ENCRYPTION_KEY' => static fn (): string => base64_encode(sodium_crypto_secretbox_keygen()),
        ];

        foreach ($secrets as $name => $factory) {
            if (!$force && $this->hasValue($existing, $name)) {
                $io->writeln(\sprintf('%s: already set in .env.local, kept', $name));
                continue;
            }

            $generated[$name] = $factory();
        }

        if ([] === $generated) {
            $io->success('All secrets are present in .env.local.');

            return Command::SUCCESS;
        }

        $content = $existing;
        if ('' !== $content && !str_ends_with($content, "\n")) {
            $content .= "\n";
        }
        if ('' === $content) {
            $content = "# Local secrets, never committed. Generated by patchnotes:secrets:generate.\n";
        }

        foreach ($generated as $name => $value) {
            $content = $this->hasValue($content, $name)
                ? (string) preg_replace(\sprintf('/^%s=.*$/m', preg_quote($name, '/')), $name.'='.$value, $content)
                : $content.$name.'='.$value."\n";
        }

        if (false === file_put_contents($envLocal, $content)) {
            $io->error(\sprintf('Cannot write %s', $envLocal));

            return Command::FAILURE;
        }
        @chmod($envLocal, 0o600);

        $io->success(\sprintf('Wrote %s to .env.local.', implode(', ', array_keys($generated))));
        $io->note('Restart the stack so that every container picks up the new values: make restart');

        return Command::SUCCESS;
    }

    private function hasValue(string $envContent, string $name): bool
    {
        if (1 !== preg_match(\sprintf('/^%s=(.*)$/m', preg_quote($name, '/')), $envContent, $matches)) {
            return false;
        }

        return '' !== trim($matches[1], " \t\"'");
    }
}
