<?php

declare(strict_types=1);

namespace App\Laws\Normalizer;

use App\Laws\Enum\LawStatus;
use App\Laws\Enum\LawType;
use App\Laws\Enum\NormStatus;
use App\Laws\Value\NormalizedLaw;
use App\Laws\Value\NormalizedNorm;
use App\Source\Value\RawDocument;

/**
 * Converts a gesetze-im-internet XML document (DTD `gii-norm` 1.01) into our Markdown format
 * (SPEC.md § 4.2, § 6.2 A). See `docs/sources/bund.gii.md` for the analysed source structure.
 *
 * **Deterministic and AI-free**: the same XML always yields byte-identical Markdown. Every diff in
 * the `laws` repository must be a real change of the law, never a rendering difference.
 */
final readonly class GiiXmlNormalizer implements LawNormalizerInterface
{
    private const string SOURCE_NAME = 'gesetze-im-internet';
    private const string BASE_URL = 'https://www.gesetze-im-internet.de';

    /** Generated by the source; our own README per law replaces it. */
    private const string TABLE_OF_CONTENTS = 'Inhaltsübersicht';

    public function __construct(
        private SentenceSplitter $sentences,
        private MarkdownEscaper $escaper,
        private NormKeyFactory $keys,
        private InlineTextRenderer $inline,
        private CalsTableRenderer $tables,
    ) {
    }

    public function supports(RawDocument $document): bool
    {
        return str_starts_with($document->content, "PK\x03\x04")
            || str_contains(substr($document->content, 0, 512), '<dokumente');
    }

    public function normalize(RawDocument $document): NormalizedLaw
    {
        $xml = $this->extractXml($document);
        $root = $this->parse($xml);

        $slug = $document->ref->id;
        $assetBase = self::BASE_URL.'/'.$slug;

        /** @var list<\DOMElement> $normElements */
        $normElements = [];
        foreach ($root->childNodes as $child) {
            if ($child instanceof \DOMElement && 'norm' === $child->nodeName) {
                $normElements[] = $child;
            }
        }

        if ([] === $normElements) {
            throw new \RuntimeException(\sprintf('Document "%s" contains no norms.', $slug));
        }

        $header = array_shift($normElements);
        $metadata = $this->lawMetadata($header, $slug);

        $norms = [];
        $keysTaken = [];
        $structure = new StructureBuilder();

        // The header norm often carries the Eingangsformel and the law-wide footnotes. When the law
        // additionally has an explicit "Eingangsformel" norm (the Grundgesetz has one), the header
        // text is kept apart instead of colliding with it.
        $headerBody = $this->renderNormBody($header, $assetBase);
        if ('' !== $headerBody) {
            $headerKey = $this->hasDesignation($normElements, 'Eingangsformel') ? 'hinweise' : 'eingangsformel';
            $norms[] = $this->makeNorm($header, $headerKey, $headerBody, \count($norms));
            $keysTaken[] = $headerKey;
        }

        foreach ($normElements as $element) {
            $designation = $this->text($element, 'metadaten/enbez');

            if (self::TABLE_OF_CONTENTS === $designation) {
                continue;
            }

            $body = $this->renderNormBody($element, $assetBase);
            $heading = $this->structureHeading($element);

            // Kapitel/Abschnitt headers carry no text of their own: they only shape the tree.
            if (null !== $heading && '' === $body && null === $designation) {
                $structure->add($heading['depth'], $heading['label'], $heading['title']);
                continue;
            }

            if (null !== $heading) {
                $structure->add($heading['depth'], $heading['label'], $heading['title']);
            }

            $key = $this->keys->unique(
                $this->keys->fromDesignation($designation, $element->getAttribute('doknr')),
                $keysTaken,
            );
            $keysTaken[] = $key;

            $norms[] = $this->makeNorm($element, $key, $body, \count($norms));
            $structure->attach($key);
        }

        return new NormalizedLaw(
            slug: $slug,
            jurisdiction: 'bund',
            type: $metadata['type'],
            status: LawStatus::InForce,
            title: $metadata['title'],
            shortTitle: $metadata['shortTitle'],
            abbreviation: $metadata['abbreviation'],
            officialAbbreviation: $metadata['officialAbbreviation'],
            dateOfIssue: $metadata['dateOfIssue'],
            promulgation: $metadata['promulgation'],
            statusNote: $metadata['statusNote'],
            lastAmendingAct: $metadata['lastAmendingAct'],
            sourceName: self::SOURCE_NAME,
            sourceUrl: $assetBase.'/',
            sourceDocumentId: '' !== $root->getAttribute('doknr') ? $root->getAttribute('doknr') : null,
            norms: $norms,
            structure: $structure->tree(),
            pendingAmendments: $metadata['pendingAmendments'],
        );
    }

    private function makeNorm(\DOMElement $element, string $key, string $body, int $position): NormalizedNorm
    {
        $designation = $this->text($element, 'metadaten/enbez');
        $title = $this->plainText($element, 'metadaten/titel');
        $status = $this->normStatus($title, $body);

        if ('' === $body) {
            // A repealed norm keeps its place in the law and says so (SPEC.md § 4.2).
            $body = NormStatus::Repealed === $status ? '(weggefallen)' : '(kein Text)';
        }

        return new NormalizedNorm(
            key: $key,
            designation: $designation,
            title: $title,
            status: $status,
            markdown: $body,
            sourceId: '' !== $element->getAttribute('doknr') ? $element->getAttribute('doknr') : null,
            position: $position,
        );
    }

    /**
     * @param list<\DOMElement> $elements
     */
    private function hasDesignation(array $elements, string $designation): bool
    {
        foreach ($elements as $element) {
            if ($designation === $this->text($element, 'metadaten/enbez')) {
                return true;
            }
        }

        return false;
    }

    /**
     * "(weggefallen)" marks a norm that has been repealed but keeps its place in the law
     * (SPEC.md § 4.2).
     */
    private function normStatus(?string $title, string $body): NormStatus
    {
        $haystack = mb_strtolower(($title ?? '').' '.$body);

        return str_contains($haystack, 'weggefallen') || str_contains($haystack, 'aufgehoben')
            ? NormStatus::Repealed
            : NormStatus::InForce;
    }

    /**
     * @return array{type: LawType, title: string, shortTitle: ?string, abbreviation: ?string, officialAbbreviation: ?string, dateOfIssue: ?\DateTimeImmutable, promulgation: ?string, statusNote: ?string, lastAmendingAct: ?string, pendingAmendments: list<string>}
     */
    private function lawMetadata(\DOMElement $header, string $slug): array
    {
        $longTitle = $this->plainText($header, 'metadaten/langue');
        $shortTitle = $this->plainText($header, 'metadaten/kurzue');
        $officialAbbreviation = $this->text($header, 'metadaten/amtabk');
        $jurabk = $this->text($header, 'metadaten/jurabk');

        $statusNotes = [];
        $lastAmendingAct = null;
        $pending = [];

        foreach ($header->getElementsByTagName('standangabe') as $stand) {
            $type = $this->text($stand, 'standtyp');
            $comment = $this->text($stand, 'standkommentar');
            if (null === $comment) {
                continue;
            }

            match ($type) {
                // "zuletzt geändert durch Art. 1 G v. 21.7.2026 I Nr. 221"
                'Stand' => $lastAmendingAct = $comment,
                // Announced but not yet incorporated — the signal for preview pull requests (§ 4.5).
                'Hinweis' => $pending[] = $comment,
                default => $statusNotes[] = $comment,
            };
        }

        // The "Stand" comment already lives in last_amending_act; status_note carries what is left
        // (re-publication notices and remarks), so the two never duplicate each other.

        return [
            'type' => $this->lawType($longTitle, $shortTitle, $officialAbbreviation),
            'title' => $longTitle ?? $shortTitle ?? $slug,
            'shortTitle' => $shortTitle,
            'abbreviation' => $officialAbbreviation ?? $jurabk,
            'officialAbbreviation' => $officialAbbreviation,
            'dateOfIssue' => $this->date($this->text($header, 'metadaten/ausfertigung-datum')),
            'promulgation' => $this->promulgation($header),
            'statusNote' => [] !== $statusNotes ? implode(' ', $statusNotes) : null,
            'lastAmendingAct' => $lastAmendingAct,
            'pendingAmendments' => $pending,
        ];
    }

    private function lawType(?string $longTitle, ?string $shortTitle, ?string $abbreviation): LawType
    {
        $haystack = mb_strtolower(($longTitle ?? '').' '.($shortTitle ?? ''));

        return match (true) {
            // "Verordnung", but also "Straßenverkehrs-Ordnung" and "Fahrerlaubnis-Verordnung".
            str_contains($haystack, 'verordnung'), str_contains($haystack, 'ordnung') => LawType::Verordnung,
            str_contains($haystack, 'bekanntmachung') => LawType::Bekanntmachung,
            str_contains($haystack, 'satzung') => LawType::Satzung,
            str_contains($haystack, 'gesetz') => LawType::Gesetz,
            null !== $abbreviation && str_ends_with($abbreviation, 'V') => LawType::Verordnung,
            default => LawType::Sonstige,
        };
    }

    private function promulgation(\DOMElement $header): ?string
    {
        foreach ($header->getElementsByTagName('fundstelle') as $fundstelle) {
            if ('amtlich' !== $fundstelle->getAttribute('typ')) {
                continue;
            }

            $periodical = $this->text($fundstelle, 'periodikum');
            $citation = $this->text($fundstelle, 'zitstelle');
            if (null !== $periodical && null !== $citation) {
                return $periodical.' '.$citation;
            }
        }

        return null;
    }

    /**
     * @return array{depth: int, label: ?string, title: ?string}|null
     */
    private function structureHeading(\DOMElement $element): ?array
    {
        $unit = $element->getElementsByTagName('gliederungseinheit')->item(0);
        if (!$unit instanceof \DOMElement) {
            return null;
        }

        $code = $this->text($unit, 'gliederungskennzahl') ?? '';

        return [
            // The source encodes nesting in the length of the sort key: three digits per level.
            'depth' => max(1, (int) ceil(\strlen($code) / 3)),
            'label' => $this->plainText($unit, 'gliederungsbez'),
            'title' => $this->plainText($unit, 'gliederungstitel'),
        ];
    }

    private function renderNormBody(\DOMElement $norm, string $assetBase): string
    {
        $blocks = [];

        foreach (['textdaten/text', 'textdaten/fussnoten'] as $path) {
            $container = $this->element($norm, $path);
            if (!$container instanceof \DOMElement) {
                continue;
            }

            $content = $this->firstChild($container, 'Content');
            if ($content instanceof \DOMElement) {
                $blocks = [...$blocks, ...$this->renderBlocks($content, $assetBase)];
            }
        }

        $footnotes = $this->renderFootnotes($norm, $assetBase);
        if ([] !== $footnotes) {
            $blocks[] = '## Fußnoten';
            $blocks = [...$blocks, ...$footnotes];
        }

        return trim(implode("\n\n", array_filter($blocks, static fn (string $b): bool => '' !== trim($b))));
    }

    /**
     * @return list<string>
     */
    private function renderBlocks(\DOMElement $container, string $assetBase): array
    {
        $blocks = [];

        foreach ($container->childNodes as $child) {
            if ($child instanceof \DOMText) {
                $text = $this->inline->render($this->wrap($child), $assetBase);
                if ('' !== $text) {
                    $blocks[] = $this->paragraph($text);
                }
                continue;
            }

            if (!$child instanceof \DOMElement) {
                continue;
            }

            $blocks = [...$blocks, ...match ($child->nodeName) {
                'P' => $this->renderParagraphElement($child, $assetBase),
                'DL' => [$this->renderList($child, $assetBase, 0)],
                'table' => [$this->tables->render($child, $assetBase)],
                'pre' => [$this->renderPre($child)],
                'Ident', 'Title', 'Subtitle' => [$this->renderHeadingLine($child, $assetBase)],
                'Revision', 'noindex' => $this->renderBlocks($child, $assetBase),
                'kommentar' => [$this->paragraph($this->inline->render($child, $assetBase))],
                // Layout and generated content of the print edition.
                'TOC', 'BR', 'FnArea', 'AttArea', 'Footnotes' => [],
                default => [$this->paragraph($this->inline->render($child, $assetBase))],
            }];
        }

        return array_values(array_filter($blocks, static fn (string $block): bool => '' !== trim($block)));
    }

    /**
     * A `P` mixes prose with lists and tables, so it is flushed piece by piece.
     *
     * @return list<string>
     */
    private function renderParagraphElement(\DOMElement $paragraph, string $assetBase): array
    {
        $blocks = [];
        $buffer = '';

        $flush = function () use (&$buffer, &$blocks): void {
            $text = trim($buffer);
            if ('' !== $text) {
                $blocks[] = $this->paragraph($text);
            }
            $buffer = '';
        };

        foreach ($paragraph->childNodes as $child) {
            if ($child instanceof \DOMElement && \in_array($child->nodeName, ['DL', 'table', 'pre'], true)) {
                $flush();
                $blocks[] = match ($child->nodeName) {
                    'DL' => $this->renderList($child, $assetBase, 0),
                    'table' => $this->tables->render($child, $assetBase),
                    default => $this->renderPre($child),
                };
                continue;
            }

            $buffer .= $this->inline->render($this->wrap($child), $assetBase).' ';
        }

        $flush();

        return array_values(array_filter($blocks, static fn (string $block): bool => '' !== trim($block)));
    }

    /**
     * One sentence per line (SPEC.md § 4.2) — the rule that makes diffs and blame meaningful.
     */
    private function paragraph(string $text): string
    {
        $lines = array_map(
            fn (string $sentence): string => $this->escaper->escapeLine($sentence),
            $this->sentences->split($text),
        );

        return implode("\n", $lines);
    }

    /**
     * DL/DT/DD lists keep the numbering printed in the law: the marker is escaped so that no
     * renderer ever renumbers an enumeration (SPEC.md § 24.2).
     */
    private function renderList(\DOMElement $list, string $assetBase, int $depth): string
    {
        $indent = str_repeat('  ', $depth);
        $lines = [];
        $marker = null;

        foreach ($list->childNodes as $child) {
            if (!$child instanceof \DOMElement) {
                continue;
            }

            if ('DT' === $child->nodeName) {
                $marker = $this->escaper->escapeListMarker($this->inline->render($child, $assetBase));
                continue;
            }

            if ('DD' !== $child->nodeName) {
                continue;
            }

            $item = $this->renderListItem($child, $assetBase, $depth, $marker);
            if ('' !== $item) {
                $lines[] = $item;
            }
            $marker = null;
        }

        return implode("\n", $lines);
    }

    private function renderListItem(\DOMElement $item, string $assetBase, int $depth, ?string $marker): string
    {
        $indent = str_repeat('  ', $depth);
        $nested = [];
        $buffer = '';

        foreach ($item->childNodes as $child) {
            if ($child instanceof \DOMElement && 'DL' === $child->nodeName) {
                $nested[] = $this->renderList($child, $assetBase, $depth + 1);
                continue;
            }

            if ($child instanceof \DOMElement && \in_array($child->nodeName, ['LA', 'Revision'], true)) {
                foreach ($child->childNodes as $grandChild) {
                    if ($grandChild instanceof \DOMElement && 'DL' === $grandChild->nodeName) {
                        $nested[] = $this->renderList($grandChild, $assetBase, $depth + 1);
                        continue;
                    }
                    $buffer .= $this->inline->render($this->wrap($grandChild), $assetBase).' ';
                }
                continue;
            }

            $buffer .= $this->inline->render($this->wrap($child), $assetBase).' ';
        }

        $sentences = $this->sentences->split($buffer);
        $text = array_map(fn (string $s): string => $this->escaper->escapeLine($s), $sentences);

        $first = array_shift($text) ?? '';
        $label = null !== $marker && '' !== $marker ? $marker.' ' : '';
        $lines = [$indent.'- '.$label.$first];

        foreach ($text as $line) {
            // Continuation sentences stay inside the list item.
            $lines[] = $indent.'  '.$line;
        }

        foreach ($nested as $sublist) {
            if ('' !== $sublist) {
                $lines[] = $sublist;
            }
        }

        return rtrim(implode("\n", $lines));
    }

    private function renderPre(\DOMElement $pre): string
    {
        $text = $pre->textContent;
        $text = str_replace(["\u{00a0}", "\r\n"], [' ', "\n"], $text);

        return "```text\n".rtrim($text)."\n```";
    }

    private function renderHeadingLine(\DOMElement $element, string $assetBase): string
    {
        $text = $this->inline->render($element, $assetBase);

        return '' !== $text ? '**'.$text.'**' : '';
    }

    /**
     * @return list<string>
     */
    private function renderFootnotes(\DOMElement $norm, string $assetBase): array
    {
        $entries = [];

        foreach ($norm->getElementsByTagName('Footnote') as $footnote) {
            $id = $footnote->getAttribute('ID');
            $label = '' !== $id ? InlineTextRenderer::footnoteLabel($id) : 'fn-'.(\count($entries) + 1);
            $text = $this->inline->render($footnote, $assetBase);

            if ('' === $text) {
                continue;
            }

            $entries[] = '[^'.$label.']: '.$text;
        }

        return $entries;
    }

    private function extractXml(RawDocument $document): string
    {
        if (!str_starts_with($document->content, "PK\x03\x04")) {
            return $document->content;
        }

        $temporary = tempnam(sys_get_temp_dir(), 'gii');
        if (false === $temporary) {
            throw new \RuntimeException('Cannot create a temporary file for the source archive.');
        }

        try {
            file_put_contents($temporary, $document->content);

            $archive = new \ZipArchive();
            if (true !== $archive->open($temporary)) {
                throw new \RuntimeException(\sprintf('Cannot open the archive of "%s".', $document->ref->id));
            }

            try {
                for ($index = 0; $index < $archive->numFiles; ++$index) {
                    $name = $archive->getNameIndex($index);
                    if (\is_string($name) && str_ends_with(strtolower($name), '.xml')) {
                        $xml = $archive->getFromIndex($index);
                        if (\is_string($xml)) {
                            return $xml;
                        }
                    }
                }
            } finally {
                $archive->close();
            }
        } finally {
            @unlink($temporary);
        }

        throw new \RuntimeException(\sprintf('The archive of "%s" contains no XML file.', $document->ref->id));
    }

    private function parse(string $xml): \DOMElement
    {
        $previous = libxml_use_internal_errors(true);

        try {
            $dom = new \DOMDocument();
            // Never resolve the external DTD or any entity: the parser must not talk to the network.
            $loaded = $dom->loadXML($xml, \LIBXML_NONET | \LIBXML_COMPACT);
            if (!$loaded || !$dom->documentElement instanceof \DOMElement) {
                $error = libxml_get_last_error();

                throw new \RuntimeException('Invalid XML: '.($error->message ?? 'unknown error'));
            }

            return $dom->documentElement;
        } finally {
            libxml_clear_errors();
            libxml_use_internal_errors($previous);
        }
    }

    private function text(\DOMElement $context, string $path): ?string
    {
        $element = $this->element($context, $path);
        if (!$element instanceof \DOMElement) {
            return null;
        }

        $text = trim((string) preg_replace('/\s+/u', ' ', str_replace("\u{00a0}", ' ', $element->textContent)));

        return '' !== $text ? $text : null;
    }

    /**
     * Like text(), but line breaks of the source become spaces and nothing is escaped: used for
     * titles, which end up in YAML front matter rather than in Markdown.
     */
    private function plainText(\DOMElement $context, string $path): ?string
    {
        $element = $this->element($context, $path);
        if (!$element instanceof \DOMElement) {
            return null;
        }

        $text = $this->inline->renderPlain($element);

        return '' !== $text ? $text : null;
    }

    private function element(\DOMElement $context, string $path): ?\DOMElement
    {
        $current = $context;
        foreach (explode('/', $path) as $step) {
            $next = $this->firstChild($current, $step);
            if (!$next instanceof \DOMElement) {
                return null;
            }
            $current = $next;
        }

        return $current;
    }

    private function firstChild(\DOMElement $element, string $name): ?\DOMElement
    {
        foreach ($element->childNodes as $child) {
            if ($child instanceof \DOMElement && $child->nodeName === $name) {
                return $child;
            }
        }

        return null;
    }

    /**
     * The inline renderer walks *children*, so a single node is wrapped in a throw-away fragment.
     */
    private function wrap(\DOMNode $node): \DOMNode
    {
        $document = $node->ownerDocument ?? new \DOMDocument();
        $fragment = $document->createDocumentFragment();
        $fragment->appendChild($node->cloneNode(true));

        return $fragment;
    }

    private function date(?string $value): ?\DateTimeImmutable
    {
        if (null === $value || 1 !== preg_match('/^\d{4}-\d{2}-\d{2}$/', $value)) {
            return null;
        }

        return \DateTimeImmutable::createFromFormat('!Y-m-d', $value) ?: null;
    }
}
